// Generated by Wrangler on Thu Jul 18 2024 21:11:45 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	DISCORD_PUBLIC_KEY: string;
	DISCORD_APPLICATION_ID: string;
	DISCORD_TOKEN: string;
	DB: D1Database;
}
