// Generated by Wrangler on Fri Jul 19 2024 16:24:32 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	BOT_LINK: "https://classywpi.kyleplo.com";
	SCHOOL_NAME: "WPI";
	DISCORD_PUBLIC_KEY: string;
	DISCORD_APPLICATION_ID: string;
	DISCORD_TOKEN: string;
	DB: D1Database;
}
