// Generated by Wrangler on Fri Jul 19 2024 16:24:32 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	BOT_NAME: "Classy for WPI";
	BOT_LINK: "https://classy.kyleplo.workers.dev";
	BOT_THEME_COLOR: "#ac2b37";
	IMPORT_PUBLIC_KEY: string,
	IMPORT_PRIVATE_KEY: string,
	DISCORD_PUBLIC_KEY: string;
	DISCORD_APPLICATION_ID: string;
	DISCORD_TOKEN: string;
	DB: D1Database;
}
